# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 12:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Price')),
                ('available', models.BooleanField(default=False, verbose_name='Active')),
                ('baths', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Bathrooms')),
                ('rooms', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Rooms')),
                ('parking', models.CharField(max_length=128, verbose_name='Parking')),
                ('floor', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Floor')),
                ('area', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Area)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
